#!/usr/bin/env bash
set -u

if [[ ${1-} == "-n" && ${2-} == "true" ]]; then
    if [[ ${MOCK_SCENARIO-} == "host-sudo-denied" ]]; then
        echo "sudo: a password is required" >&2
        exit 1
    fi
    exit 0
fi

if [[ ${1-} == "-n" ]]; then
    shift
fi
exec "$@"
